### ISSUE TITLE
关于ORL数据测试代码

### ISSUE THREAD

**Issue by aoko-sys** [huybery/huybery-blog#2]
作者您好！
我是一名学生，正在研究您这篇论文的代码！因为ORL相对于RGBD数据集是已经提前好特征的数据集，ORL数据集是不需要在进行卷积操作，所以不能直接套用您已经开源的代码，不知您能否把ORL数据的代码发给我？（emial：1064435762@qq.com）或者Wechat（15674717770），我也给您发来邮件！期待您能够回复！感激不尽

**Comment by huybery** [comment]
Unrelated issues closed.
